services:
  endpoint:
    image: node:18
    user: node
    command: sh -c "tail -f /dev/null"
    container_name: sisgha-endpoint
    # restart: always
    working_dir: /code
    depends_on:
      - endpoint-db
      - endpoint-meilisearch
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/code
    networks:
      - sisgha-net

  endpoint-db:
    image: bitnami/postgresql:15
    container_name: sisgha-endpoint-db
    # restart: always
    volumes:
      - 'sisgha-endpoint-db-data:/bitnami/postgresql'
      - './volumes/db/scripts/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d'
    env_file:
      - .db.env
    networks:
      - sisgha-net
    ports:
      - 5432:5432

  endpoint-meilisearch:
    image: getmeili/meilisearch:v1.0.2
    container_name: sisgha-endpoint-meilisearch
    # restart: always
    ports:
      - 7700:7700
    env_file:
      - .meilisearch.env
    volumes:
      - 'sisgha-endpoint-meilisearch-data:/meili_data'
    networks:
      - sisgha-net


networks:
  sisgha-net:

volumes:
  sisgha-endpoint-db-data:
  sisgha-endpoint-meilisearch-data:
